export enum ActionType {
    ALL_POSTS_ACTIVE = 'ALL_POSTS_ACTIVE',
    CREATOR_PROFILE_ACTIVE = 'CREATOR_PROFILE_ACTIVE',
    POSTS_REQUEST_LOADING = 'POSTS_REQUEST_LOADING',
    POSTS_REQUEST_SUCCESS = 'POSTS_REQUEST_SUCCESS',
    POSTS_REQUEST_ERROR = 'POSTS_REQUEST_ERROR',
}