export enum ActionType {
    ALL_POSTS_ACTIVE = 'ALL_POSTS_ACTIVE',
    CREATOR_PROFILE_ACTIVE = 'CREATOR_PROFILE_ACTIVE',
    POSTS_REQUEST_LOADING = 'POSTS_REQUEST_LOADING',
    POSTS_REQUEST_SUCCESS = 'POSTS_REQUEST_SUCCESS',
    POSTS_REQUEST_ERROR = 'POSTS_REQUEST_ERROR',
    COMMENTS_REQUEST_LOADING = 'COMMENTS_REQUEST_LOADING',
    COMMENTS_REQUEST_SUCCESS = 'COMMENTS_REQUEST_SUCCESS',
    COMMENTS_REQUEST_ERROR = 'COMMENTS_REQUEST_ERROR',
    USERS_REQUEST_LOADING = 'USERS_REQUEST_LOADING',
    USERS_REQUEST_SUCCESS = 'USERS_REQUEST_SUCCESS',
    USERS_REQUEST_ERROR = 'USERS_REQUEST_ERROR',
}